<?xml version="1.0"?>

<robot name = "differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- camera dimention-->
<xacro:property name="camera_link" value="0.1"/>
<!-- body dimention-->
<xacro:property name="body_link_x_dim" value="1.0"/>
<xacro:property name="body_link_y_dim" value="0.6"/>
<xacro:property name="body_link_z_dim" value="0.3"/>


<!-- wheel dimention-->
<xacro:property name="wheel_link_radius" value="0.15"/>
<xacro:property name="wheel_link_length" value="0.1"/>
<xacro:property name="wheel_link_z_location" value="-0.1"/>


<!-- Material density-->
<xacro:property name="body_density" value="2710.0"/>
<xacro:property name="wheel_density" value="2710.0"/>


<!-- PI constant-->
<xacro:property name="pi_const" value="3.14159265"/>


<!-- robot body and wheel mass-->
<xacro:property name="body_mass" value="${body_density*body_link_x_dim*body_link_y_dim*body_link_z_dim}"/>
<xacro:property name="wheel_mass" value="${wheel_density*pi_const*wheel_link_radius*wheel_link_radius*wheel_link_length}"/>



<!-- moments of inertia of the wheel-->
<xacro:property name="Iz_wheel" value="${0.5*wheel_mass*wheel_link_radius*wheel_link_radius}"/>
<xacro:property name="I_wheel" value="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}"/>

<!-- the complete inertial sectio, of the wheel-->
<xacro:macro name="inertia_wheel">
	<inertial>
	<origin rpy="0 0 0" xyz="0 0 0"/>
	<mass value="${wheel_mass}"/>
	<inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0" izz="${Iz_wheel}" />
	</inertial>
</xacro:macro>

<!-- gazebo define control driver-->
<xacro:include filename="$(find robot_model_pkg)/urdf/robot.gazebo" />


<link name="dummy">
</link>
<joint name="dummy_joint" type="fixed">
	<parent link="dummy" />
	<child link="body_link" />
</joint>


<!-- $$$$$$$ start body link $$$$$$$$-->
<link name="body_link">
	<visual>
		<geometry>
			<box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
		</geometry>
	<origin rpy="0 0 0" xyz="0 0 0"/>
	</visual>
	
	<collision>
		<geometry>
			<box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
		</geometry>
		<origin rpy="0 0 0" xyz="0 0 0"/>
	</collision>
	
	<inertial>
		<origin rpy="0 0 0" xyz="0 0 0"/>
		<mass value="${body_mass}"/>
	<inertia 
	ixx="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim + body_link_z_dim*body_link_z_dim)}"
	ixy="0"
	ixz="0"
	iyy="${(1/12)*body_mass*(body_link_x_dim*body_link_x_dim+body_link_z_dim*body_link_z_dim)}"
	iyz="0"
	izz="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_x_dim*body_link_x_dim)}"/>
	</inertial>
</link>

<!-- $$$$$$$ end body link $$$$$$$$-->



<!-- $$$$$$$ start wheel back right $$$$$$$$-->

<joint name="wheel1_joint" type="continuous" >
	<parent link="body_link"/>
	<child link="wheel1_link"/>
	<origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
	<axis xyz="0 1 0" />
	<limit effort="1000" velocity="1000"/>
	<dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel1_link">
	<visual>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</visual>
	
	<collision>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</collision>
	
	<xacro:inertia_wheel/>
</link>

<!-- $$$$$$$ start wheel back left $$$$$$$$-->

<joint name="wheel2_joint" type="continuous" >
	<parent link="body_link"/>
	<child link="wheel2_link"/>
	<origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
	<axis xyz="0 1 0" />
	<limit effort="1000" velocity="1000"/>
	<dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel2_link">
	<visual>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</visual>
	
	<collision>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</collision>
	
	<xacro:inertia_wheel />
</link>

<!-- $$$$$$$ start wheel front right $$$$$$$$-->

<joint name="wheel3_joint" type="continuous" >
	<parent link="body_link"/>
	<child link="wheel3_link"/>
	<origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
	<axis xyz="0 1 0" />
	<limit effort="1000" velocity="1000"/>
	<dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel3_link">
	<visual>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</visual>
	
	<collision>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</collision>
	
	<xacro:inertia_wheel />
</link>

<!-- $$$$$$$ start wheel front left $$$$$$$$-->

<joint name="wheel4_joint" type="continuous" >
	<parent link="body_link"/>
	<child link="wheel4_link"/>
	<origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0" />
	<axis xyz="0 1 0" />
	<limit effort="1000" velocity="1000"/>
	<dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel4_link">
	<visual>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</visual>
	
	<collision>
		<origin rpy="1.570795 0 0" xyz="0 0 0"/>
		<geometry>
			<cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
		</geometry>
	</collision>
	
	<xacro:inertia_wheel />
</link>


  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.5 0 0" rpy="0 0 0"/>
    <parent link="body_link"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="Green"/>
    </visual>

    <inertial>
      <mass value="0.1" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

</robot>
